### ISSUE TITLE
Question about analyzing data containing time-dependent covariates

### ISSUE THREAD

**Issue by clarinetrefle** [hputter/mstate#24]
I would like to do multi-state modeling using mstate package based on data containing time-dependent covariates. The data I would like to use are, for example, the attached data. The subject's BMI value changes over time, and are time-dependent covariates. Three types of subject status are assumed: "no disease", "with disease", and "death". With this data, I would like to evaluate the association between BMI and risk of transitioning to each status.
 Is it possible to analyze data containing such time-dependent covariates with the use of mstate package or can I use some other software to analyze the data?

Each column in the attached data means the following
・id：Subject’s ID
・stt：Time when the individual started to be followed, with the start of the follow-up to 0 (Unit : years)
・sts：Status at “stt” (0 : No disease, 1 : Disease, 2 : Death)
・illt：Time of transition to disease state or time of last follow-up, with the start of the follow-up to 0 (Unit : years)
・ills：Event occurrence at “illt” (0 : censoring, 1 : disease(transition))
・dt：Time when the transition to the death state occurred or the last follow-up time, with the start of the follow-up set to 0 (Unit : years)
・ds：Event occurrence at “dt” (0 : censoring, 1 : death(transition))
・BMIt_X：Time when BMI was measured (The number in X indicates how many times the measurement has been taken) (Unit : years)
・BMIs_X：Measured BMI values (The number in X indicates how many times the measurement has been taken)
・x1：sex (covariate)

<img width="796" alt="スクリーンショット 2023-04-18 131809" src="https://user-images.githubusercontent.com/130441160/232670376-bddee5b3-4990-4996-9494-8f97a8154075.png">

**Comment by stanleyrazor** [comment]
@clarinetrefle , were you able to get a solution to your question ?
I am stuck in a similar position.
Kind regards,
Stanley

**Comment by edbonneville** [comment]
@clarinetrefle really sorry for the delay in answering.. in your example, your time-dependent covariate (BMI) is _endogenous_ (further reading [here](https://www.annualreviews.org/content/journals/10.1146/annurev-statistics-030718-105048)), so for transition-specific association estimation I think you should be using a joint model with a multi-state submodel. You should be able to do this using the  [`{JMbayes2}`](https://drizopoulos.github.io/JMbayes2/articles/Multi_State_Processes.html) package.

You can estimate transition-specific hazards with exogenous time-dependent continuous covariates using `{mstate}`, but this will need a little more data preparation and you will not be able to use `probtrans()`. I think at the moment this is easier to do with the `{msm}` package, see [here](https://chjackson.github.io/msm/msmcourse/timedep.html#timedep).

**Comment by clarinetrefle** [comment]
@edbonneville I apologize for the late reply. Thank you your detailed response.
